name: Build Project Plan
on: [push]

jobs:
  # Build TJ Report
  build_report:
    runs-on: ubuntu-slim
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Show OS info
        run: |
          uname -a
          cat /etc/os-release
      - name: Update APT
        run: |
          sudo apt-get update

      - name: Install ruby
        run: sudo apt-get install ruby-full

      - name : Install Taskjuggler
        run: sudo gem install taskjuggler

      - name: Check Taskjuggler
        run: |
          tj3 --version

      - name: List all files
        run: |
          find .
          mkdir build
          cat > build/index.html << EOF
          <!doctype html>
          <html>
          <head> <title>This is the title of the webpage!</title> </head>
          <body> <p>This is an example paragraph. Anything in the <strong>body</strong> tag will appear on the page, just like this <strong>p</strong> tag and its contents.</p> </body>
          </html>
          EOF
      - name: Upload result as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/
  # Deployment Job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-slim
    needs: build_report
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
